version: "2"

services:
  data:
    image: busybox
    container_name: "manager_data"
    volumes:
      - /data
      - /var/lib/mysql

  redis:
    image: redis
    container_name: "manager_redis"
    ports:
      - "6379:6379"
    volumes_from:
      - data

  mysql:
    image: mysql:5.7
    container_name: "manager_mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    volumes_from:
      - data

  front:
    image: abiosoft/caddy
    container_name: "manager_caddy"
    environment:
      - CADDYPATH=/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/Caddyfile
      - ./.docker/caddy/caddyssl:/etc/caddycerts
    depends_on:
      - app
    volumes_from:
      - app

  app:
    image: manager_skeleton:build
    build: .
    container_name: "manager_app"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    command: /usr/local/sbin/php-fpm --allow-to-run-as-root

  cron:
    image: manager_skeleton:build
    build: .
    container_name: "manager_cron"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
      - app
    command: /usr/local/bin/start